### ISSUE TITLE
No One is your session 

### ISSUE THREAD

**Issue by udy786** [chornyitaras/PBXWebPhone#10]
Hi, 

As you included image that it should show Ready. Its showing ready but when agent to login it should ring and stay connected but its saying no one is your session.

Is working for anyone in vicidial?

**Comment by chornyitaras** [comment]
It would not ring until agent press "call agent webphone"
![image](https://cloud.githubusercontent.com/assets/17271728/23547784/3616b0bc-000d-11e7-87be-0b2c2f8a3456.png)
