### ISSUE TITLE
Audio issue- Disconnecting call for lack of RTP activity in 61 seconds

### ISSUE THREAD

**Issue by rushikpatelrushikapatel2010** [chornyitaras/PBXWebPhone#11]
I have followed your steps and configured this module and it seems to be working fine except audio issue.

My system information is as below:

**Admin Vicidial Information**
VERSION: 2.14-611a
BUILD: 170425-1353 
© 2017 ViciDial Group

**Agent Vicidial Information**
VERSION: 2.14-520c       
BUILD: 170416-1640

**Asterisk Version**
Asterisk 11.25.1-vici

Log for rtp is as below:

> 
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033387, ts 480640, len 000160)
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033388, ts 480800, len 000160)
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033389, ts 480960, len 000160)
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033390, ts 481120, len 000160)
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033391, ts 481280, len 000160)
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033392, ts 481440, len 000160)
> [Apr 28 03:33:33] Sent RTP packet to      xxx.xxx.xxx.xxx:58125 (type 00, seq 033393, ts 481600, len 000160)
> 

When agent is logging in, and press call Agent webphone:

> [Apr 28 06:57:14]   == Using SIP RTP CoS mark 5
> [Apr 28 06:57:15]        > Channel SIP/5555-00000002 was answered
> [Apr 28 06:57:15]     -- Executing [8600052@default:1] MeetMe("SIP/5555-00000002", "8600052,F") in new stack
> [Apr 28 06:57:15]   == Parsing '/etc/asterisk/meetme.conf': Found
> [Apr 28 06:57:15]   == Parsing '/etc/asterisk/meetme-vicidial.conf': Found
> [Apr 28 06:57:15]     -- Created MeetMe conference 1023 for conference '8600052'
> [Apr 28 06:57:15]     -- <SIP/5555-00000002> Playing 'conf-onlyperson.gsm' (language 'en')
> 
> 
> [Apr 28 06:57:46] NOTICE[7292]: chan_sip.c:29370 check_rtp_timeout: Disconnecting call 'SIP/5555-00000002' for lack of RTP activity in 61 seconds
> [Apr 28 06:57:46]     -- Hungup 'DAHDI/pseudo-1305219282'
> 
> [Apr 28 06:57:46]   == Spawn extension (default, 8600052, 1) exited non-zero on 'SIP/5555-00000002'
> [Apr 28 06:57:46]     -- Executing [h@default:1] AGI("SIP/5555-00000002", "agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----44---------------") in new stack

It looks like issue with RTP, we have already opened rtp port range from firewall.

Can you please suggest me how to make it working?
Is there anything wrong in configuration?

Please let me know.

**Comment by chornyitaras** [comment]
looks liike NAT related issue
