### ISSUE TITLE
Dialpad!

### ISSUE THREAD

**Issue by tedd77** [chornyitaras/PBXWebPhone#12]
Hello,
After long research I landed on PBXWebPhone, it worked without any tweaking except for dialpad.
Am I missing something here? I could not seem to find a way to call out. 
Also the auto-answer ! why should it be always enabled ?
This project is great and very simple, it lacks the following
1. Dialpad unless it is there and I cannot find
2. Auto answer not always on
3. Ring tones.

Hope to see some collaboration on this
Thank you

**Comment by chornyitaras** [comment]
hi @tedd77 
At this moment there is no dialpad implemented. 
regarding autoanswer I have a plan  to make it optional  see issue #3

**Comment by tedd77** [comment]
hi @chornyitaras 
Thank you for your reply. Do you plan to add a dialpad ? and by when ?
I was hoping to use your software for a project. It was the only one that worked for me out of the box but then no dialpad and the auto answer put me on hold.

**Comment by chornyitaras** [comment]
i will add optional auto answer in next few weeks. regarding dialpad - current it is in backlog. Anyway you can implement dialpad and create a pull request:)

**Comment by chornyitaras** [comment]
resolved by 0f05986c269aa05a88161efdd0396967020cca2e
