### ISSUE TITLE
MultiServer

### ISSUE THREAD

**Issue by ngtechnologies** [chornyitaras/PBXWebPhone#13]
Want to say that this is a great addition and saves time in setting up new agents and phones. My question is, in a multi-server setup we create the phones but are currently creating a template for each asterisk server. After phone creation we need to assign template to each phone, if we create 3 phones to load balance, we have to change template in each phone. Is there an easier way to accomplish this?

**Comment by chornyitaras** [comment]
@ngtechnologies  why do you need 3 different templates. I believe that you can have same template for all servers. 
only difference - path to the cert file. However you can have same path on all servers(by creating symlinks)
