### ISSUE TITLE
WebPhone hanging up

### ISSUE THREAD

**Issue by edvalbuena** [chornyitaras/PBXWebPhone#14]
I was testing this webphone for vicidial and I encountered this 

[Jun 17 14:53:38] ERROR[25141][C-00000001]: res_rtp_asterisk.c:2131 __rtp_recvfrom: DTLS failure occurred on RTP instance '0x7f3508010da8' due to reason 'missing tmp ecdh key', terminating
[Jun 17 14:53:38] WARNING[25141][C-00000001]: res_rtp_asterisk.c:4234 ast_rtp_read: RTP Read error: Unspecified.  Hanging up.

any clue on how to resolve this hurdle?

**Comment by chornyitaras** [comment]
@edvalbuena are you using Firefox?

**Comment by edvalbuena** [comment]
yeah i am

**Comment by chornyitaras** [comment]
Try chrome:). Asterisk 11 does not work with latest Firefox. There is a way to fix this by patching asterisk. You can find more info here: https://community.asterisk.org/t/error-missing-tmp-ecdh-key-when-receiving-call-over-webrtc-tls/66271

**Comment by edvalbuena** [comment]
Now I get this

DOMException [InvalidSessionDescriptionError: "Invalid description, no ice-ufrag attribute"
code: 0
nsresult: 0x0]

**Comment by chornyitaras** [comment]
Can you please share more details. Are you compiling asterisk from sources?

**Comment by edvalbuena** [comment]
Yeah I was using vicidial's asterisk 11.

I keep getting ice-ufrag error. and the webphone kept on disconnecting.

**Comment by chornyitaras** [comment]
Check this https://stackoverflow.com/questions/33887661/invalidsessiondescriptionerror-invalid-description-no-ice-ufrag-attribute

**Comment by chornyitaras** [comment]
Closing this issue cause not a webpbone one but asterisk
