### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by 90s-nerd** [chornyitaras/PBXWebPhone#16]
I have followed your guide to install webphone on the server. But getting the below error in Chrome dev console.

`WebSocket connection to 'wss://domain.com:8089/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

All the certificates are properly installed.

Also added firewall exceptions.

**Comment by chornyitaras** [comment]
Can you open in your web browser https://domain.com:8089/ws?

Also please check if asterisk is listening port 8089

netstat -ln | grep 8089

**Comment by chornyitaras** [comment]
please also take a look  here #7

**Comment by 90s-nerd** [comment]
@chornyitaras 

Can you open in your web browser https://domain.com:8089/ws?
This returns "Site can't be reached error"

netstat -ln | grep 8089 is not returning any output.

I am using the latest version of ViciDial v8.0.1 with asterisk 11

I already tried the solutions from #7 and still same error. If required I can give you remote access.

**Comment by chornyitaras** [comment]
looks like asterisk http server is not configured correctly.
please follow this guide 
https://github.com/chornyitaras/PBXWebPhone/wiki/Asterisk-configuration

**Comment by chornyitaras** [comment]
@sajeelmuhammed  did it help? can I close this issue?
