### ISSUE TITLE
Firefox Test

### ISSUE THREAD

**Issue by navaer** [chornyitaras/PBXWebPhone#17]
Hi, I have been testing with firefox (different versions and different OS), it rings the first time and show it as answered, but there is no sound, a few seconds after it returns a message "No one is in your session" but webphone is still in answer state. This doesn't happen with chrome, in chrome everything works fine. Have you tested in a specific firefox version?

![imagen](https://user-images.githubusercontent.com/17253660/34139522-e57a52e0-e43a-11e7-8107-fe18408f8b04.png)

**Comment by chornyitaras** [comment]
Hi @navaer,
Unfortunately asterisk 11 does not work with latest Firefox. please see #14  for more details

**Comment by chornyitaras** [comment]
hi @navaer  this issue is not reproducible when asterisk 13 is used.
You can find information about upgrading asterisk here:
http://www.vicidial.org/VICIDIALforum/viewtopic.php?f=8&t=37864
