### ISSUE TITLE
Webphone Issue han_sip.c: 4258 _sip reliable_xmit: Serious Network Trouble; _sip xmit

### ISSUE THREAD

**Issue by luqman27180** [chornyitaras/PBXWebPhone#22]
hi @chornyitaras 

[Jan 23 16:31:03] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:07] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:15] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:17] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:21] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:29] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:31] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:35] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:43] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:45] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:49] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:57] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:31:59] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:32:03] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:32:11] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data
[Jan 23 16:32:13] ERROR[16280] chan_sip.c: Serious Network Trouble; __sip_xmit returns error for pkt data

i am getting this error any idea?

asterisk 11.25

**Comment by chornyitaras** [comment]
usually this is harmless.
