### ISSUE TITLE
Unable to reach webphone

### ISSUE THREAD

**Issue by amitiyer** [chornyitaras/PBXWebPhone#25]
Hello, 

I am facing the below issue which logging in the campaign, Asterisk shows this. cannot request the channel.

channel.c:5690 __ast_request_and_dial: Unable to request channel SIP/gs102

**Comment by amitiyer** [comment]
any update ?

**Comment by chornyitaras** [comment]
Do you see "Ready" on your webphone iframe?

**Comment by amitiyer** [comment]
Yes, i can see READY on the webphone iframe

**Comment by amitiyer** [comment]
Hello,

Now i am receiving the calls but the call is not being autoanswered, Asterisksays Channel (extension) was never answered.
