### ISSUE TITLE
Mute option

### ISSUE THREAD

**Issue by navaer** [chornyitaras/PBXWebPhone#4]
Add an option for mute when the call is setup

**Comment by chornyitaras** [comment]
There is mute option in vicidial. I don't think that it needs to be duplicated in web phone.

**Comment by navaer** [comment]
Thanks for your replay, we are testing your phone in goautodial, everything works fine, but for some reason the project goautodial deleted the mute option. I see that you hace a function inside the phone code to mute but I dont know how to call it from a javascript-button

**Comment by chornyitaras** [comment]
It's not a function. It's event handler.

**Comment by chornyitaras** [comment]
I'll try to add experimental support later today

**Comment by chornyitaras** [comment]
One more think AFAIK Goautodial uses asterisk v1.8 which  does not support webrtc. Are you using webrtc2sip?

**Comment by navaer** [comment]
I'm using external pbx Asterisk 11 Webrtc, calling url webphone from goautodial,  thats why I'm trying ti ger the mute button for your phone to mute the webrtc channel

**Comment by chornyitaras** [comment]
please checkout this branch 
https://github.com/chornyitaras/PBXWebPhone/tree/mute_option

**Comment by navaer** [comment]
I have been testing the branch and everything works great!

**Comment by chornyitaras** [comment]
Feature has been merged to master
