### ISSUE TITLE
Real Time Monitoring error

### ISSUE THREAD

**Issue by ngtechnologies** [chornyitaras/PBXWebPhone#6]
At first was error not finding index.php, so copied PBXWebPhone folder to vicidial folder and now Real Time screen finds the index.php. However, have websocket connection error....yet agent phones work on this same server.

**Comment by chornyitaras** [comment]
hi @ngtechnologies 
can you pls add more information about your setup. As I understand from your comment you are trying to integrate this webphone with vicidial admin interface. Is my understanding correct?

**Comment by ngtechnologies** [comment]
HelloThank you for the quick reply, as the webphone has been working perfect and made my life more simple.Our system is multi-server, 1 database, 1 web/asterisk, and 1 asterisk only. Yes, I would like to have the webphone working in the Real Time screen to monitor calls. As I a stated before, I have the PBXWebphone folder in agc folder and works for agents....when I set a supervisor phone as webphone the webphone iframe showed error of /vicidial/PBXWebphone/index not found. So, I also copied the PBXWebphone into the vicidial folder (where the admin php files are) and now the webphone is in the iframe but shows error connecting to websockets. This is on my web/asterisk server, and i have agents already using the webphone on this same server. Something else I have noticed is that if I try and use the load-balancing of phones with alias', the phones will not work when connected to the other server and show websocket errors.I appreciate any and all support.  

-------- Original Message --------
Subject: Re: [chornyitaras/PBXWebPhone] Real Time Monitoring error (#6)

**Comment by chornyitaras** [comment]
To have webphone working on real time report screen you need to provide phone credentials and asterisk server info using url arguments 
for example:
`https://domain/PBXWebPhone/index.php?&phone_login=ODAwNw==&phone_pass=ODAwNw== ...`

**Required** arguments
- phone_login
- phone_pass
- server_ip
- options

**ALL data is encoded using base64** 

options example data (w/o encoding)
`INITIAL_LOAD--DIALPAD_OFF_TOGGLE--AUTOANSWER_Y--DIALBOX_Y--MUTE_Y--VOLUME_Y--WEBSOCKETURLwss://domain.com:8089/ws`
