### ISSUE TITLE
Webphone works from campaign but not Reports

### ISSUE THREAD

**Issue by slickric01** [chornyitaras/PBXWebPhone#9]
I have the Webphone working great from within campaigns. When I access the Realtime Report (/vicidial/realtime_report.php#) there's a link to Webphone on the top right which opens an iframe with an error: 
Got wrong web socker url. Please check your settings

Any chance it can work from the reports screen to realtime monitor.

Thanks.

**Comment by chornyitaras** [comment]
In vicidial ADMINISTRATION page change Admin->System Settings->Webphone URL 
from PBXWebPhone/index.php to https://YOUR_VICIDIAL_DOMAIN_NAME/agc/PBXWebPhone/index.php for example:  https://example.com/agc/PBXWebPhone/index.php

**Comment by slickric01** [comment]
I actually tried that. I get the same error.

**Comment by slickric01** [comment]
I noticed one difference between the iframe of the working webphone in the campaign and the one that doesn't work in the report:

Report:
var options = 'INITIAL_LOAD--DIALPAD_OFF_TOGGLE--AUTOANSWER_Y';

Campaign:
var options = 'INITIAL_LOAD--DIALPAD_Y--AUTOANSWER_Y--DIALBOX_Y--MUTE_Y--VOLUME_Y--WEBSOCKETURLwss://MY_VICIDIAL_DOMAIN:8089/ws';

**Comment by chornyitaras** [comment]
yes this is the case: 
vicidial does not send web sockets URL:
apply this patch 
[vici.txt](https://github.com/chornyitaras/PBXWebPhone/files/780544/vici.txt)

**Comment by chornyitaras** [comment]
@slickric01 did it help? Can I close this issue?

**Comment by slickric01** [comment]
Yes. It works now. Thanks for your help.
